[theme]
base = "light"
primaryColor = "#1248F5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#111111"
font = "sans serif"

[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
